### ISSUE TITLE
broken for Safari

### ISSUE THREAD

**Issue by itsmhuang** [citation-js/date#15]
When I `const Cite = require('citation-js');` in my code, it doesn't work on Safari (it works in Chrome, Firefox, etc).

The error message in the console is `SyntaxError: Invalid regular expression: invalid group specifier name`, and it's pointing to this line of code: `var dateRangeDelimiters = / (?:to|[-/]) | ?(?:--|[–—]) ?|(?<=\d{4}-\d{2}-\d{2})\/(?=\d{4}-\d{2}-\d{2})/;`

According to my research, Safari doesn't support lookbehind, as in `(?<=\` https://caniuse.com/js-regexp-lookbehind

Can you fix this so that it works in Safari?

**Comment by larsgw** [comment]
Thank you for reporting this. I think I hoped at the time Babel would transform it into something that was supported. I will look into it.

**Comment by larsgw** [comment]
I made a new release for `@citation-js/date` but to include it in `citation-js` you would have to rebuild your bundle locally, until I make a new release, and I am not planning on doing that immediately (it might still be soon though).

**Comment by itsmhuang** [comment]
@larsgw thank you so much! Looking forward to it.
